apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'streaming-data-loader'
        static_configs:
          - targets: [ 'streaming-data-loader:8000' ]
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'localhost:9090' ]
      - job_name: 'node_exporter'
        static_configs:
          - targets: [ 'node_exporter:9100' ]
      - job_name: 'cadvisor'
        static_configs:
          - targets: [ 'cadvisor:8080' ]
